name: to_do_list
description: A beautiful Flutter To-Do app with login, task lists, PDF export, and theme switching.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  email_validator: ^2.1.17
  path_provider: ^2.1.2
  pdf: ^3.10.7
  share_plus: ^7.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1  # Add this line

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"  # Make sure this image exists
  min_sdk_android: 21  # Optional

flutter:
  uses-material-design: true

  assets:
    - assets/img/background.jpg
